apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: sqpknlovg-go-gitops
  description: This is GitOps manifest for sqpknlovg-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=sqpknlovg-go
    backstage.io/kubernetes-id: sqpknlovg-go 
    backstage.io/techdocs-ref: dir:. 
    jenkins.io/job-full-name: sqpknlovg-go-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:sqpknlovg-go
